apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog-prod
  labels:
    app: blog
    project: blog
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      project: blog
      environment: prod
  template:
    metadata:
      labels:
        app: blog
        project: blog
        environment: prod
    spec:
      containers:
      - name: blog
        image: registry.abyssworks.dev/blog:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres:5432/blog
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: production
        - name: HOSTNAME
          value: "0.0.0.0"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog-prod
  labels:
    app: blog
    project: blog
    environment: prod
spec:
  selector:
    app: blog
  ports:
  - port: 80
    targetPort: 3000
